// Task titles as students type them, labeled by whether the "Plan it" pill should show:
// would a breakdown into days help, or would offering one feel patronizing? `BIG` and `SMALL`
// were labeled before the check was written (the old keyword check got 53/62 and 43/73). The
// check was then tuned on them, so `UNSEEN_*` came after: titles it hadn't seen, scored once
// before any change (32/35 and 46/46; the old check 29/35 and 29/46). Its three misses were
// fixed as patterns (a "book report" leading, packing up a whole room, "moving out"). Tune on
// these, then judge a change on a fresh unseen batch the same way. `EITHER` holds the honest
// coin flips; they're never asserted.

/** Bigger than one sitting, or too vague to start: offer Plan it. */
export const BIG = [
  'Study for orgo midterm',
  'Write 10-page history paper',
  'Write 5-page history paper on WWI',
  'Clean my room',
  'Essay',
  'History essay',
  'History essay due Friday',
  'Figure out what to do about summer housing',
  'Chem midterm',
  'Orgo final',
  'Prepare for job interview',
  'Prep for calc exam',
  'Research paper on climate policy',
  'Start lit review',
  'Work on capstone project',
  'Finish lab report',
  'Lab report',
  'Apply to summer internships',
  'Internship applications',
  'Do my taxes',
  'Taxes',
  'FAFSA',
  'Fill out FAFSA',
  "Plan Mia's birthday party",
  'Organize closet',
  'Declutter the garage',
  'Pack for the move',
  'Move out of dorm',
  'Build portfolio website',
  'Learn Spanish basics',
  'Revise personal statement',
  'Personal statement',
  'Group presentation',
  'Make slides for presentation',
  'Senior thesis',
  'Study for driving test',
  'Get ready for the career fair',
  'Catch up on bio lectures',
  'Review for stats final',
  'Write my novel',
  'Deep clean the apartment',
  'College essays',
  'Scholarship applications',
  'Grad school applications',
  'Practice for the recital',
  'Learn to code',
  'Cover letter for Deloitte',
  'Finish the essay',
  'start essay',
  'study',
  'Clean the kitchen',
  'Chem: study for unit 3 test',
  'cram for bio exam',
  'Memorize lines for the play',
  'Train for the 5k',
  'Studying for the LSAT',
  'Research grad programs',
  'Final project',
  'Work on research proposal',
  'Rewrite intro of thesis',
  'Get my whole life organized before the semester starts',
  'Things to sort before moving into the new apartment',
];

/** One sitting and obvious how to begin: no pill. */
export const SMALL = [
  'Walk Biscuit',
  'Buy stamps',
  'Call mom',
  'Read ch. 4',
  'Reply to Prof. Alvarez',
  'Email Dr. Ruiz about the quiz',
  'Text Sam about the project',
  'Email TA about the essay deadline',
  'Submit the essay',
  'Turn in lab report',
  'Print the paper',
  'Print lab report',
  'Book flight home',
  'Schedule advising appointment',
  'Pay rent',
  'Pick up prescription',
  'Drop off library books',
  'Return Amazon package',
  'Buy poster board for the project',
  'Sign up for the midterm review session',
  'Register for spring classes',
  'Ask Jordan for the lecture notes',
  'Check grades',
  'Look up the exam room',
  'Download the study guide',
  'Upload homework to Canvas',
  'Take out trash',
  'Do laundry',
  'Water plants',
  'Cancel gym membership',
  'Venmo Alex for pizza',
  'Make dentist appointment',
  'Watch lecture 7',
  "RSVP to Sarah's party",
  'Stretch',
  'Go to the gym',
  'Meet with study group',
  'Attend office hours',
  'Remind Sam about the essay',
  'Send resume to recruiter',
  'Write thank-you note to grandma',
  'Write grocery list',
  'Write down homework',
  'Charge laptop',
  'Feed the cat',
  'Shower',
  'Clean the litter box',
  'Wash dishes',
  'Pack lunch',
  'Get groceries',
  'Grocery shopping',
  'Finish reading ch. 5',
  'Review notes before class',
  'Fix bike tire',
  'Email professor about an extension',
  'Talk to advisor about switching majors',
  'Buy toilet paper',
  'Pay the application fee',
  'Move car for street cleaning',
  'Watch the final',
  'Report the broken heater',
  'Follow up with the landlord',
  'Call the pharmacy about my refill',
  'Text the group chat about Friday',
  'Pick up report card',
  'Cook dinner',
  'Order textbooks for chem',
  'Ask for an extension on the essay',
  'Return library book',
  'Renew parking pass',
  'Confirm interview time',
  'watch baseball',
  'Email Ms. Patel the permission slip for the field trip',
];

export const UNSEEN_BIG = [
  'Spanish oral presentation', 'Write lab report for chem', 'Study for physics final', 'Book report on Of Mice and Men',
  'Prepare speech for best man', 'Research for history project', 'Get started on my portfolio', 'Work on resume',
  'Draft cover letter', 'MCAT prep', 'Studying for GRE', 'Apply to grad schools', 'Organize my notes for the final',
  'Clean out the garage', 'Tidy bedroom', 'Pack up my dorm room', 'Moving out', 'Plan spring break trip', 'Learn guitar',
  'Build a resume', 'English paper', 'Psych research paper', 'Final exam review', 'Midterm prep', 'Write college essay',
  'Senior project', 'Revise draft of lab report', 'Do FAFSA', 'File taxes', 'Start on my dissertation',
  'Rehearse the presentation', 'Website redesign', 'Sort out my finances before the semester', 'Get ready for finals',
  'Practice coding interview questions',
];

export const UNSEEN_SMALL = [
  'Email Professor Kim', 'Text mom happy birthday', 'Call the dentist', 'Buy printer ink', 'Return the rental car',
  'Submit lab report on Canvas', 'Print my essay before class', 'Ask TA about the exam format', 'Book study room',
  'Pay phone bill', 'Pick up dry cleaning', 'Drop off the essay at the office',
  'Schedule a meeting with my advisor about my thesis', 'Reply to the group project email',
  'Read chapter 7 for the midterm', 'Watch the lecture on photosynthesis', 'Go to the career center',
  'Attend the review session', 'Check if the paper was graded', 'Buy blue books for the exam', 'Sign the lease',
  'Send the presentation to Jordan', 'Email my group our slides', 'Upload the final project', 'Turn in the application',
  'Make a doctor appointment', 'Clean my glasses', 'Take vitamins', 'Feed Biscuit', 'Get a haircut', 'Change the sheets',
  'Do the dishes', 'Take out recycling', 'Venmo rent', 'Write a note for Mia', 'Plan tomorrow', 'RSVP to the career fair',
  'Register for the LSAT', 'Cancel Spotify', 'Order a cap and gown', 'Meet Sam at the library', "Tell Jordan I can't make it",
  'Look up office hours', 'Download Zoom', 'Charge AirPods', 'Remind roommate about rent',
];

/** Coin flips: never asserted. */
export const EITHER = [
  'Quiz',
  'Bio quiz',
  'Math homework',
  'Homework',
  'Update resume',
  'Proofread essay',
  'Make flashcards for the exam',
  'Outline the essay',
  'Read The Great Gatsby',
  'Decide on a major',
  'Renew passport',
  'Apply for parking permit',
  'Edit video',
  'Plan dinner party',
  'Move to Chicago',
  'Do problem set 4',
  'Plan my week',
  'Apply for financial aid',
];
